package com.star.foodfans.dao;

import com.star.foodfans.entity.Achievemenkindtinfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AchievemenkindtinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    int insert(Achievemenkindtinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    Achievemenkindtinfo selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    List<Achievemenkindtinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Achievemenkindtinfo record);
}