package com.star.foodfans.dao;

import com.star.foodfans.entity.Articleinfo;
import com.star.foodfans.entity.Videoinfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Mapper
public interface ArticleinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer articleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleinfo
     *
     * @mbggenerated
     */
    int insert(Articleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleinfo
     *
     * @mbggenerated
     */
    Articleinfo selectByPrimaryKey(Integer articleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleinfo
     *
     * @mbggenerated
     */
    List<Articleinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Articleinfo record);

    List<Articleinfo> selectArticleCollectionByUserid(int userid);

    List<Articleinfo> selectArticlePublishByUserid(int userid);

    List<Articleinfo> selectArticleHistoryByUserid(int userid);

    List<Articleinfo> getHotArticles();

    List<Map> searchArticles(String dish, String cuisine);

    List<Articleinfo> selectTen();
}