package com.star.foodfans.dao;

import com.star.foodfans.entity.Commentinfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface CommentinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    int insert(Commentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    Commentinfo selectByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    List<Commentinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Commentinfo record);

    List<Commentinfo>  selectByContentid(String contentid);
}