package com.star.foodfans.dao;

import com.star.foodfans.entity.Friendrange;
import java.util.List;

import com.sun.imageio.plugins.common.I18N;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FriendrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userid") Integer userid, @Param("friendid") Integer friendid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    int insert(Friendrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    Friendrange selectByPrimaryKey(@Param("userid") Integer userid, @Param("friendid") Integer friendid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    List<Friendrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Friendrange record);

    List<Friendrange> selectPersonalFriends(Integer userid);

}