package com.star.foodfans.dao;

import com.star.foodfans.entity.Userinfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    Userinfo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    List<Userinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userinfo record);

    int insertByEmail(String username, String email, String password);

    int updateUserInfo(Integer userid, String username, String headpicture, String phone);

    Userinfo selectByEmail(String email);

    String selectPasswordByUserid(Integer userid);

    int changePassword(Integer userid, String newPassword);

    int changePasswordByEmail(String email, String newPassword);

//    List<Articleinfo> selectCollectionByUserid(int userid);
//
//    List<Articleinfo> selectPublishByUserid(int userid);
//
//    List<Articleinfo> selectHistoryByUserid(int userid);

    List<Userinfo> selectNameByArticle(Integer articleid);
    List<Userinfo> selectNameByVideo(Integer articleid);

}