package com.star.foodfans.dao;

import com.star.foodfans.entity.Videoinfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface VideoinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videoinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer videoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videoinfo
     *
     * @mbggenerated
     */
    int insert(Videoinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videoinfo
     *
     * @mbggenerated
     */
    Videoinfo selectByPrimaryKey(Integer videoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videoinfo
     *
     * @mbggenerated
     */
    List<Videoinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videoinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Videoinfo record);

    List<Videoinfo> selectVideoCollectionByUserid(int userid);

    List<Videoinfo> selectVideoPublishByUserid(int userid);

    List<Videoinfo> selectVideoHistoryByUserid(int userid);

    List<Videoinfo> selectByHot();

}